{% set name = "scripting" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/csdms/py-scripting/archive/v{{ version }}.tar.gz
  fn: py-scripting-{{ version }}.tar.gz
  sha256: 889b7d5971b8f9b74188f92dc8166790a6c25a5319181094619a6cb0e3877cbf

requirements:
  build:
    - setuptools
    - python
    - pip
    - nose
    - pbr
  run:
    - python
    - nose
    - six

test:
  imports:
    - scripting
  commands:
    - nosetests --with-doctest scripting

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

about:
  home: https://github.com/csdms/py-scripting
  license: MIT
  license_file: LICENSE
  summary: Python utilities for shell scripting
  dev_url: https://github.com/csdms/py-scripting
