{% set name = "scripting" %}
{% set version = "0.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/csdms/py-scripting/archive/v{{ version }}.tar.gz
  fn: py-scripting-{{ version }}.tar.gz
  sha256: 7ff93a9af586c93a41808f5132f75dc58c9a383abe702c5e5a87cc95f9585670

requirements:
  build:
    - setuptools
    - python
    - pip
    - pytest
  run:
    - python
    - pytest
    - six

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs scripting --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

about:
  home: https://github.com/csdms/py-scripting
  license: MIT
  license_file: LICENSE
  summary: Python utilities for shell scripting
  dev_url: https://github.com/csdms/py-scripting
