{% set name = "scripting" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/csdms/py-scripting/archive/v0.2.0.tar.gz

requirements:
  build:
    - setuptools
    - python
    - nose
    - pbr
  run:
    - python
    - nose
    - six

test:
  imports:
    - scripting
  commands:
    - nosetests --with-doctest scripting

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

about:
  home: https://github.com/csdms/py-scripting
  license: MIT
  license_file: LICENSE
  summary: Python utilities for shell scripting
  dev_url: https://github.com/csdms/py-scripting
